apiVersion: v1
kind: Service
metadata:
  name: awwvision-webapp
  labels:
    app: awwvision
    role: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: "http-server"
  selector:
    app: awwvision
    role: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: awwvision-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awwvision
      role: frontend
  template:
    metadata:
      labels:
        app: awwvision
        role: frontend
    spec:
      containers:
      - name: awwvision-webapp
        image: gcr.io/$GCLOUD_PROJECT/awwvision-webapp
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: redis-master
        - name: GCLOUD_PROJECT
          value: $GCLOUD_PROJECT
        ports:
        - name: http-server
          containerPort: 8080
