/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-02-04 at 16:40:17 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.vision.v1.model;

/**
 * External image source (i.e. Google Cloud Storage image location).
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Vision API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ImageSource extends com.google.api.client.json.GenericJson {

  /**
   * Google Cloud Storage image URI. It must be in the following form:
   * "gs://bucket_name/object_name". For more details, please see:
   * https://cloud.google.com/storage/docs/reference-uris. NOTE: GCS object versioning is not
   * supported!
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gcsImageUri;

  /**
   * Google Cloud Storage image URI. It must be in the following form:
   * "gs://bucket_name/object_name". For more details, please see:
   * https://cloud.google.com/storage/docs/reference-uris. NOTE: GCS object versioning is not
   * supported!
   * @return value or {@code null} for none
   */
  public java.lang.String getGcsImageUri() {
    return gcsImageUri;
  }

  /**
   * Google Cloud Storage image URI. It must be in the following form:
   * "gs://bucket_name/object_name". For more details, please see:
   * https://cloud.google.com/storage/docs/reference-uris. NOTE: GCS object versioning is not
   * supported!
   * @param gcsImageUri gcsImageUri or {@code null} for none
   */
  public ImageSource setGcsImageUri(java.lang.String gcsImageUri) {
    this.gcsImageUri = gcsImageUri;
    return this;
  }

  @Override
  public ImageSource set(String fieldName, Object value) {
    return (ImageSource) super.set(fieldName, value);
  }

  @Override
  public ImageSource clone() {
    return (ImageSource) super.clone();
  }

}
